"""identity persistence baseline

Revision ID: 20260724_0001
Revises:
Create Date: 2026-07-24 19:31:07.871104
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20260724_0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("oidc_issuer", sa.String(length=2048), nullable=False),
        sa.Column("oidc_subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("deletion_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("purge_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'pending_deletion')", name=op.f("ck_users_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("oidc_issuer", "oidc_subject", name=op.f("uq_users_oidc_issuer")),
    )
    op.create_index(op.f("ix_users_purge_after"), "users", ["purge_after"], unique=False)
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        "ix_audit_events_user_time", "audit_events", ["user_id", "occurred_at"], unique=False
    )
    op.create_table(
        "chat_threads",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_chat_threads_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_threads")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_chat_threads_id")),
    )
    op.create_index(op.f("ix_chat_threads_user_id"), "chat_threads", ["user_id"], unique=False)
    op.create_table(
        "flight_searches",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("criteria", sa.JSON(), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_flight_searches_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flight_searches")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_flight_searches_id")),
    )
    op.create_index(
        op.f("ix_flight_searches_expires_at"), "flight_searches", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_flight_searches_user_id"), "flight_searches", ["user_id"], unique=False
    )
    op.create_table(
        "flight_watches",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("criteria", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_flight_watches_positive_version")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_flight_watches_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flight_watches")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_flight_watches_id")),
    )
    op.create_index(
        "ix_flight_watches_due", "flight_watches", ["status", "next_run_at"], unique=False
    )
    op.create_index(op.f("ix_flight_watches_user_id"), "flight_watches", ["user_id"], unique=False)
    op.create_table(
        "outbox_events",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("topic", sa.String(length=120), nullable=False),
        sa.Column("aggregate_type", sa.String(length=80), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_outbox_events_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_outbox_events_idempotency_key")),
    )
    op.create_index(
        "ix_outbox_events_ready", "outbox_events", ["published_at", "available_at"], unique=False
    )
    op.create_index(op.f("ix_outbox_events_user_id"), "outbox_events", ["user_id"], unique=False)
    op.create_table(
        "traveler_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=80), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("legal_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("gender_marker", sa.String(length=30), nullable=True),
        sa.Column("birth_date_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("nationality_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("passport_number_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("passport_issuing_country_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("passport_expiry_date_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("encryption_key_version", sa.Integer(), nullable=False),
        sa.Column("consent_version", sa.String(length=40), nullable=False),
        sa.Column("consented_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_traveler_profiles_positive_version")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_traveler_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_traveler_profiles")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_traveler_profiles_id")),
        sa.UniqueConstraint("user_id", "label", name=op.f("uq_traveler_profiles_user_id")),
    )
    op.create_index(
        op.f("ix_traveler_profiles_user_id"), "traveler_profiles", ["user_id"], unique=False
    )
    op.create_index(
        "uq_traveler_profiles_one_default_per_user",
        "traveler_profiles",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("is_default"),
        sqlite_where=sa.text("is_default = 1"),
    )
    op.create_table(
        "user_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("session_token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("device_label", sa.String(length=120), nullable=True),
        sa.Column("user_agent_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_user_sessions_id")),
        sa.UniqueConstraint("session_token_hash", name=op.f("uq_user_sessions_session_token_hash")),
    )
    op.create_index(
        "ix_user_sessions_user_expiry", "user_sessions", ["user_id", "expires_at"], unique=False
    )
    op.create_table(
        "agent_checkpoints",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("thread_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("state_schema_version", sa.Integer(), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("version > 0", name=op.f("ck_agent_checkpoints_positive_version")),
        sa.ForeignKeyConstraint(
            ["thread_id", "user_id"],
            ["chat_threads.id", "chat_threads.user_id"],
            name="thread_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_checkpoints")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_agent_checkpoints_id")),
        sa.UniqueConstraint("thread_id", "version", name=op.f("uq_agent_checkpoints_thread_id")),
    )
    op.create_index(
        op.f("ix_agent_checkpoints_user_id"), "agent_checkpoints", ["user_id"], unique=False
    )
    op.create_table(
        "chat_messages",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("thread_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("client_message_id", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "role IN ('user', 'assistant', 'system', 'tool')", name=op.f("ck_chat_messages_role")
        ),
        sa.ForeignKeyConstraint(
            ["thread_id", "user_id"],
            ["chat_threads.id", "chat_threads.user_id"],
            name="thread_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_messages")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_chat_messages_id")),
        sa.UniqueConstraint(
            "thread_id", "client_message_id", name="uq_chat_messages_thread_client_message"
        ),
        sa.UniqueConstraint("thread_id", "sequence", name="uq_chat_messages_thread_sequence"),
    )
    op.create_index(
        "ix_chat_messages_thread_chronology",
        "chat_messages",
        ["thread_id", "sequence", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_chat_messages_user_id"), "chat_messages", ["user_id"], unique=False)
    op.create_table(
        "flight_offers",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("search_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("provider_offer_id", sa.String(length=512), nullable=False),
        sa.Column("offer_snapshot", sa.JSON(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["search_id", "user_id"],
            ["flight_searches.id", "flight_searches.user_id"],
            name="search_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flight_offers")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_flight_offers_id")),
        sa.UniqueConstraint(
            "provider", "environment", "provider_offer_id", name=op.f("uq_flight_offers_provider")
        ),
    )
    op.create_index(
        "ix_flight_offers_user_expiry", "flight_offers", ["user_id", "expires_at"], unique=False
    )
    op.create_index(op.f("ix_flight_offers_user_id"), "flight_offers", ["user_id"], unique=False)
    op.create_table(
        "watch_matches",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("watch_id", sa.Uuid(), nullable=False),
        sa.Column("deduplication_key", sa.String(length=160), nullable=False),
        sa.Column("offer_snapshot", sa.JSON(), nullable=False),
        sa.Column(
            "matched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["watch_id", "user_id"],
            ["flight_watches.id", "flight_watches.user_id"],
            name="watch_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watch_matches")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_watch_matches_id")),
        sa.UniqueConstraint(
            "watch_id", "deduplication_key", name=op.f("uq_watch_matches_watch_id")
        ),
    )
    op.create_index(op.f("ix_watch_matches_user_id"), "watch_matches", ["user_id"], unique=False)
    op.create_index(
        "ix_watch_matches_watch_time", "watch_matches", ["watch_id", "matched_at"], unique=False
    )
    op.create_table(
        "watch_runs",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("watch_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.String(length=120), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["watch_id", "user_id"],
            ["flight_watches.id", "flight_watches.user_id"],
            name="watch_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watch_runs")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_watch_runs_id")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_watch_runs_idempotency_key")),
    )
    op.create_index(
        "ix_watch_runs_due_lease", "watch_runs", ["scheduled_for", "lease_expires_at"], unique=False
    )
    op.create_index(op.f("ix_watch_runs_user_id"), "watch_runs", ["user_id"], unique=False)
    op.create_table(
        "booking_intents",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("source_offer_id", sa.Uuid(), nullable=False),
        sa.Column("thread_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("traveler_profile_ids", sa.JSON(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_booking_intents_positive_version")),
        sa.ForeignKeyConstraint(
            ["source_offer_id", "user_id"],
            ["flight_offers.id", "flight_offers.user_id"],
            name="offer_owner",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["thread_id", "user_id"],
            ["chat_threads.id", "chat_threads.user_id"],
            name="thread_owner",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_booking_intents_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booking_intents")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_booking_intents_id")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_booking_intents_idempotency_key")),
    )
    op.create_index(
        "ix_booking_intents_user_status", "booking_intents", ["user_id", "status"], unique=False
    )
    op.create_table(
        "bookings",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("booking_intent_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=True),
        sa.Column("provider_order_id", sa.String(length=512), nullable=True),
        sa.Column("payment_customer_reference", sa.String(length=512), nullable=True),
        sa.Column("payment_method_reference", sa.String(length=512), nullable=True),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_bookings_positive_version")),
        sa.ForeignKeyConstraint(
            ["booking_intent_id", "user_id"],
            ["booking_intents.id", "booking_intents.user_id"],
            name="intent_owner",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_bookings_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookings")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_bookings_id")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_bookings_idempotency_key")),
        sa.UniqueConstraint("provider", "provider_order_id", name=op.f("uq_bookings_provider")),
    )
    op.create_index("ix_bookings_user_status", "bookings", ["user_id", "status"], unique=False)
    op.create_table(
        "booking_events",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["booking_id", "user_id"],
            ["bookings.id", "bookings.user_id"],
            name="booking_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booking_events")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_booking_events_id")),
    )
    op.create_index(
        "ix_booking_events_booking_time",
        "booking_events",
        ["booking_id", "occurred_at"],
        unique=False,
    )
    op.create_index(op.f("ix_booking_events_user_id"), "booking_events", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision for development and migration smoke tests."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_booking_events_user_id"), table_name="booking_events")
    op.drop_index("ix_booking_events_booking_time", table_name="booking_events")
    op.drop_table("booking_events")
    op.drop_index("ix_bookings_user_status", table_name="bookings")
    op.drop_table("bookings")
    op.drop_index("ix_booking_intents_user_status", table_name="booking_intents")
    op.drop_table("booking_intents")
    op.drop_index(op.f("ix_watch_runs_user_id"), table_name="watch_runs")
    op.drop_index("ix_watch_runs_due_lease", table_name="watch_runs")
    op.drop_table("watch_runs")
    op.drop_index("ix_watch_matches_watch_time", table_name="watch_matches")
    op.drop_index(op.f("ix_watch_matches_user_id"), table_name="watch_matches")
    op.drop_table("watch_matches")
    op.drop_index(op.f("ix_flight_offers_user_id"), table_name="flight_offers")
    op.drop_index("ix_flight_offers_user_expiry", table_name="flight_offers")
    op.drop_table("flight_offers")
    op.drop_index(op.f("ix_chat_messages_user_id"), table_name="chat_messages")
    op.drop_index("ix_chat_messages_thread_chronology", table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_agent_checkpoints_user_id"), table_name="agent_checkpoints")
    op.drop_table("agent_checkpoints")
    op.drop_index("ix_user_sessions_user_expiry", table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index(
        "uq_traveler_profiles_one_default_per_user",
        table_name="traveler_profiles",
        postgresql_where=sa.text("is_default"),
        sqlite_where=sa.text("is_default = 1"),
    )
    op.drop_index(op.f("ix_traveler_profiles_user_id"), table_name="traveler_profiles")
    op.drop_table("traveler_profiles")
    op.drop_index(op.f("ix_outbox_events_user_id"), table_name="outbox_events")
    op.drop_index("ix_outbox_events_ready", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index(op.f("ix_flight_watches_user_id"), table_name="flight_watches")
    op.drop_index("ix_flight_watches_due", table_name="flight_watches")
    op.drop_table("flight_watches")
    op.drop_index(op.f("ix_flight_searches_user_id"), table_name="flight_searches")
    op.drop_index(op.f("ix_flight_searches_expires_at"), table_name="flight_searches")
    op.drop_table("flight_searches")
    op.drop_index(op.f("ix_chat_threads_user_id"), table_name="chat_threads")
    op.drop_table("chat_threads")
    op.drop_index("ix_audit_events_user_time", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_index(op.f("ix_users_purge_after"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
